targets:
  c_x11_activity_monitor_backend:
    tool: cc
    type: staticlib
    path: util/activity-monitor
    input:
      - c_x11_activity_monitor_backend.c
    packages:
      - x11
      - xtst
      - xi
  
  activity_monitor:
    tool: vala
    type: staticlib
    path: util/activity-monitor
    input:
      - ActivityMonitor.vala
      - X11ActivityMonitorBackend.vala
    uses:
      - c_x11_activity_monitor_backend
    packages:
      - gdk-x11-3.0
      - glib-2.0
  
  util:
    tool: vala
    type: staticlib
    path: util
    input:
      - CleverTimeout.vala
      - Countdown.vala
      - IFocusManager.vala
    packages:
      - glib-2.0
  
  brainbreak:
    tool: vala
    type: program
    input:
      - break/BreakType.vala
      - break/BreakModel.vala
      - break/BreakView.vala
      - break/TimerBreakStatusWidget.vala
      - break/TimerBreakModel.vala
      - break/TimerBreakView.vala
      - microbreak/MicroBreakType.vala
      - microbreak/MicroBreakModel.vala
      - microbreak/MicroBreakView.vala
      - restbreak/RestBreakType.vala
      - restbreak/RestBreakModel.vala
      - restbreak/RestBreakView.vala
      - BreakManager.vala
      - BreakOverlay.vala
      - BreakFocusManager.vala
      - main.vala
      - ScreenOverlay.vala
      - UIManager.vala
    defines:
      - GETTEXT_PACKAGE="brainbreak"
    uses:
      - common
      - util
      - activity_monitor
      - c_x11_activity_monitor_backend
    packages:
      - glib-2.0
      - gio-2.0
      - gtk+-3.0
      - gee-1.0
      - libnotify

