project:
  name:     Brain Break
  version:  1
  url:      http://www.dylanmccall.com


requires:
  x11:
    type: package
    version: 1.4.99.1
    mandatory: True
  xtst:
    type: package
    version: 1.2.0
    mandatory: True
  xi:
    type: package
    version: 1.5.99.3
    mandatory: True
  gdk-x11-3.0:
    type: package
    mandatory: True
  glib-2.0:
    type: package
    mandatory: True
  gio-2.0:
    type: package
    version: 2.30.0
    mandatory: True
  gio-unix-2.0:
    type: package
    version: 2.30.0
    mandatory: True
  gtk+-3.0:
    type: package
    version: 3.0.8
    mandatory: True
  gee-1.0:
    type: package
    version: 0.6.2
    mandatory: True
  libnotify:
    type: package
    version: 0.4.5
    mandatory: True

subdirs:
  - settings
  - helper

targets:
  common:
    tool: vala
    type: staticlib
    path: common
    input:
      - NaturalTime.vala
    defines:
      - GETTEXT_PACKAGE="brainbreak"
    packages:
      - glib-2.0

